### PR TITLE
GOO, HER, LOB, SCA persist

### PR DESCRIPTION
**Pull request by jcaracappa1**
## Summary 
- GOO, HER, LOB, and SCA persist 
- Additional changes to other species to improve overall biomass

## Parameter Changes
- at_biology.prm:
  - mum/C adjustments for SCA, LOB, BMS, MAK, HER, WHK, WIF, WTF, PLA, MPF, BUT, BPF, GOO, SHK, POL, SCU, TYL, RED, STB, FDF, and DOG
  - Removed mQ for SCA, LOB, WHK, BUT, SCU, ST, YTF, and DOG
  - Adjusted mQ for HER and GOO
  - Adjusted fixed recruitment (KDENR) for WPF, BPF, and OPT
  - Adjusted B-H alpha/beta for MAK, SUF, WIF, MPF, BUT, BPF, GOO, SHK, POL, and STB
 - neus_init.nc : Adjusted initial conditions so that individual RN:SN for most age-structured groups was 2 instead of 2.65 (Relevent size-at-age csv's were adjusted too)  

## Other changes
- make_diet_changes.R : Edited to remove predation for testing
- plot_yearlyoutput_function.R : Modified Hem's script to work for neus-atlantis file structure

### CODE REVIEW

**Comment by jcaracappa1** [comment]
@gambler1650 @andybeet Not perfect but a lot better. A few species crashing as a result but this was the first run in ages where GOO, HER, LOB, and SCA were all persisting till the end. Tidying up merge conflict with function now.

**Comment by jcaracappa1** [comment]
[ Fix_GOO_MAK_Pull_RequestModel_Comparison_Biomass.pdf](https://github.com/NOAA-EDAB/neus-atlantis/files/9454770/Fix_GOO_MAK_Pull_RequestModel_Comparison_Biomass.pdf)

**Comment by jcaracappa1** [comment]
@andybeet @gambler1650 Merge conflict fixed

**Comment by andybeet** [comment]
@gambler1650 looks good to me

**Comment by gambler1650** [comment]
Looks good @jcaracappa1, @andybeet 

Merging

**Pull request merged**
