### PR TITLE
STB, RHK, POL, WIF fixes

### PR DESCRIPTION
**Pull request by gambler1650**
All groups being worked on for total biomass 'cycling' issues or persistence issues are stable and persisting, with good age structures.

Groups still to be worked on for age structure issues are BLF and BSB

### CODE REVIEW

**Comment by gambler1650** [comment]
@andybeet, @jcaracappa1

**Comment by jcaracappa1** [comment]
@gambler1650 It looks like the FSP values for WHK, BLF, and WPF got duplicated instead of replaced?

**Comment by gambler1650** [comment]
@jcaracappa1 

Those three are ones I didn't work on this time through... Do you mean they should be different?

The ones I did work on: some of them it looks like I already merged in an earlier pull request (or maybe you added those values in manually at some point after I told you them, before your last pull request)?

All the values for the species I was working on are correct in this branch's at_biology.prm file (double and triple checked)

**Comment by jcaracappa1** [comment]
@gambler1650 I'm not really sure what's going on then. When I look at the diff for the at_biology file (I also saw it on your branch) there are two copies of FSP_WJL, FSP_BLF, and FSP_WPF. I don't see that on my branch. They're identical though, so just deleting one set would fix it.

**Comment by andybeet** [comment]
@gambler1650, @jcaracappa1  Looking at the diagnostics (`biomIndx.txt`) for output in folder WIF_132. All pass persistence and stability. This run does correspond to file listed here. However as there is some duplication (like @jcaracappa1 mentioned) in the `at_biology.prm.file` i am guessing Atlantis uses the parameter values of the most recent line it reads in. If this is the case, then this may be a problem, since the lines added (that appear in green) appear first in the order and therefore may not actually be used

**Comment by gambler1650** [comment]
Ah, I understand now.  Was a bit dense last night.  Fixed on my branch, will do another pull request.

**Pull request closed without merging**
