### PR TITLE
Diet Audit & Adjustments

### PR DESCRIPTION
**Pull request by jcaracappa1**
## Summary
- Used the stomach contents dataset to change high priority diets
- Some growth/mortality/diet adjustments to groups after diet changes
- New script to change initial fish condition
- built working example for diet changes

### CODE REVIEW

**Comment by jcaracappa1** [comment]
@gambler1650 @andybeet

**Comment by andybeet** [comment]
what is this file? https://github.com/NOAA-EDAB/neus-atlantis/pull/165/files#diff-615eac4c2926594f660f91a5e18f283292039a7561cf5dcdf2348b746cd93c52
can you also delete the gitleaks action?
otherwise looks good

**Comment by jcaracappa1** [comment]
@andybeet  Accentually committed one of those temp files that get generated.

**Comment by jcaracappa1** [comment]
I disabled the workflow. Not sure if I can delete those

**Comment by gambler1650** [comment]
@andybeet @jcaracappa1 Looks good to me, merging.

**Pull request merged**
