### PR TITLE
Keeps track of completed status in initialization file to start from …

### PR DESCRIPTION
**Pull request by gambler1650**
…the first not completed run

Keeps track of completed status in initialization file to start fromthe first not completed run
Also eliminates the wait between runs, as it keeps polling the log file to see when the run actually starts

### CODE REVIEW

**Comment by gambler1650** [comment]
@andybeet @jcaracappa1

**Comment by andybeet** [comment]
There are a lot of hard coded paths. Assuming we will generalize later on?

**Comment by jcaracappa1** [comment]
@gambler1650 Would it be possible to convert these paths to variables in the function? Otherwise I'm likely to miss some

**Comment by gambler1650** [comment]
> @gambler1650 Would it be possible to convert these paths to variables in the function? Otherwise I'm likely to miss some

@jcaracappa1 , Will work on that.  Taking off at about 11, but if you have any questions, feel free to text me at 508-274-0334

**Pull request closed without merging**
