### PR TITLE
Planktivore persist atlnts 7

### PR DESCRIPTION
**Pull request by gambler1650**
Check to see if this merge looks good.

### CODE REVIEW

**Comment by gambler1650** [comment]
@andybeet @jcaracappa1 to check

**Comment by andybeet** [comment]
@gambler1650 @jcaracappa1 This shouldn't be right now. The at_biology files (plus other at_ files) do not follow the naming convention we planned upon. The idea is that we have just **one** at_biology file (and one at_forcing file etc.) so we do not proliferate the folder with names of files that do not fit the convention. The file at_biology_test.prm should be used and the commit should reference what changed, rather than the file name. The same for other at_ files.

**Comment by gambler1650** [comment]
Ok, will clean this up on Thursday and do it again. @andybeet @jcaracappa1

**Comment by jcaracappa1** [comment]
@andybeet @gambler1650 Where would be a good place to keep record of all the "failed" attempts (the ones that don't ultimately be kept). Would that go in the ReadMe that Andy made?

**Pull request closed without merging**
