### PR TITLE
All Groups Persist

### PR DESCRIPTION
**Pull request by jcaracappa1**
## Summary
Initially aimed to rebalance HER, MAK, and ZL interactions. Ended up getting all groups to persist and reduced the biomass of the more extreme species' biomass. 

### New Files
- R/Project_Batcher_Template.R - Generalized script to run multiple types of parameter changes in the same run batch
- R/atlantis_batcher.r - Incorporated atlantis batcher function and modified to account for current workflow
- R/call_run_comparisons_batcher.r - Template script to setup and use atlantis_batcher.r
- R/make_BHalpha_param_files.R - Creates new biology.prm files with Beverton-Holt alpha/beta changes
- R/make_catch_scale_scenarios.R - Creates alternative catch forcing (totalcatch.ts) based on timing and scalar
- R/make_fishing_intensity.R - Creates diagnostic that orders species by mean fishing mortality
- R/make_mQ_param_files.R - Creates new biology.prm files with quadratic mortality changes
- R/make_mumC_param_files.R - Creates new biology.prm files with growth or clearance rate changes
- R/make_radar_plot.R - Function to create radar plots of multiple runs
- R/make-radial_plot_set_guild - Wrapper to take a run set and a baseline run and create relative comparisons as radar plots
- R/make_run_set_PCA.R - Creates a PCA and biplot of a run set to compare species composition between runs
- R/plot_age_structure.R - Creates summary plot of guild-level age distribution
- R/plot_run_comparisons_batcher.R - Function to take arbitrary batches of runs and plot biomass comparisons of all run sets within
- diagnostics/expected_age_structure.csv - Reference age structure for plotting
- diagnostics/fishing_intensity.csv - Categorizes mean fishing mortality
- currentVersion/CatchFiles/total_catch_base.ts - Backup of catch for manipulating with functions

### Parameter Changes
- currentVersion/CatchFiles/total_catch.ts - Reduce HER catch during spinup
- currentVersion/at_biology.prm 
-- Clearance rate changes for: SCA, BMS, MAK, HER, WHK, SUF, WIF, BUT, BPF, GOO, MEN, SHK, POL, SCU, RED, OPT, STB, FDF, and DOG
-- Growth rate changes for SCA, BMS, HER, WHK, SUF, WIF, BUT, BPF, GOO, MEN, SHK, POL, SCU, RED, OPT, STB, FDF, and DOG
-- Quadratic mortality changes for BMS, MAK, HER, SUF, BUT, BPF, SHK, POL, SCU, OPT, and YTF
-- KDENR changes for WPF, PLA, BPF, and TAU
-- BHalpha changes for MAK, HER, WHK, BLF, SUF, WIF, BUT, POL, BSB, and STB
-- BHbeta changes for MAK, SUF, WIF, MPF, GOO, and STB
- currentVersion/neus_init.nc - Rescale most species to have initial RN:SN of 2, rescaled initial biomass at age to be more central

### Script Changes
- R/edit_catch_spinup.R - changed working example
- R/edit_init_age_distribution.R - Reworked prescribed age distribution options to work better with other functions
- R/edit_param_RN_init.R - Redefine default parameters and comment out working example
- R/edit_param_mum_shape.R - Comment out working example
- R/make_age_distribution.R - Removed rounding so output sums exactly to 1
- R/process_atl_output.R - Fixed bug in diet processing
- R/scale_catch.R - Converted to wrapper to use scale_catch_functions.R
- R/scale_catch_functions.R - Reworked to be used with other functions
- R/test_post_processing.R - Changed paths

### Other Changes
- diagnostics/Initial_Size_Age.csv - diagnostic updated with neus_init.nc changes
- diagnostics/StockSmart_Initial_Numbers.csv - diagnostic updated with neus_init.nc changes
- diagnostics/StockSmart_Numbers_Initial_Conditions.csv  - diagnostic updated with neus_init.nc changes
- diagnostics/functional_group_match.csv - Changed full names to match case of neus_groups.csv
- .gitignore - Removed parameter archive from version control

### CODE REVIEW

**Comment by jcaracappa1** [comment]
[Dev_11032022 biomass timeseries.pdf](https://github.com/NOAA-EDAB/neus-atlantis/files/9939571/Dev_11032022.
[ Dev_11032022Model_Comparison_Biomass.pdf](https://github.com/NOAA-EDAB/neus-atlantis/files/9939575/Dev_11032022Model_Comparison_Biomass.pdf)
biomass.timeseries.pdf)

**Comment by jcaracappa1** [comment]
[Dev_11032022 biomass timeseries.pdf](https://github.com/NOAA-EDAB/neus-atlantis/files/9939581/Dev_11032022.biomass.timeseries.pdf)

**Comment by jcaracappa1** [comment]
@andybeet @gambler1650 Big pull request. Lots of new additions and changes.

**Comment by andybeet** [comment]
Nice, Looks like most species end up in ball park of initial biomass. Only a few run away species eg. POL (but improved from previous), WHK, SCA (a little worse)

**Comment by gambler1650** [comment]
Looks great to me!  Good job.

**Pull request merged**
