### PR TITLE
ATLNTS-104 New COBALT Forcing

### PR DESCRIPTION
**Pull request by jcaracappa1**
Broadly this is just an update of the correct COBALT v10 output, and includes the ROMS-aggregations scripts, ROMS diagnostics, forcing generation, forcing diagnostics, and Atlantis integration steps. Some scripts have just been updated for a more consistent file naming and directory organization. The biggest change to the final forcing is that the alternative (non-Hydroconstruct) routine was used for temperature and salinity so that it's consistent with the other box variables. 

## Updated Atlantis Files
- at_force_WINDOWS.prm
- CurrentVersion/tsfiles/Annual_Files/roms_tempsalt_*.nc

## New Scripts 
- fix_force_scalevars.R allows rescaling of forcing variables of a constant
- make_ROMS_files_2.R Is a revised ROMS-processing script that allows for a more general input file structure. It also includes flags for different variable groups depending on need. 
- make_force_statevar generalized to work on groups of variable names (all nutrients in one file, all LTL variables in another, etc.)

## Updated Scripts
- ROMS_Diagnostics
- forcing_diagnostics
- updated calls and file paths/names for most scripts/calls relating to the creating and plotting of ROMS/forcing files

### CODE REVIEW

**Comment by jcaracappa1** [comment]
@andybeet @gambler1650 I think everything should merge properly. Rob might want to test running Atlantis from this repo on his machine before merge just to make sure. Output looks good on my end though

**Comment by gambler1650** [comment]
@andybeet @jcaracappa1 

This looks good to me from the description and I won't be able to check the run until tomorrow.  If it holds things up I'd suggest merging it.

**Comment by andybeet** [comment]
looks good to me too. @gambler1650, there is no rush to merge. why don't you check this tomorrow then if all is well merge.

**Comment by andybeet** [comment]
@jcaracappa1 @gambler1650. So there is a conflict with the file make_force_path.R. Let's wait until joe gets back to resolve this.

**Comment by jcaracappa1** [comment]
Alright I see what happened. I did some more more on that script for the new output after I already changed it some for Andy. I'll take care of it.

**Comment by jcaracappa1** [comment]
@gambler1650 @andybeet I want to hold off on the merge until I can fix this issue with the extra directory. Seems to be a folder case issue. We don't want an additional "CurrentVersion" folder

**Comment by gambler1650** [comment]
So everything still looks good to me, and it ran on my machine with no problems.  Menhaden looks a bit problematic, but should be an easy fix.  Whenever the CurrentVersion issue is fixed, it can be merged.

**Comment by andybeet** [comment]
@gambler1650 looks good. merge !

**Pull request merged**
