### PR TITLE
update catch data methods

### PR DESCRIPTION
**Pull request by andybeet**
## Pull and process catch data

Result = `neusCatchData.rds`

*  `create_comlandr_US_catch.r` - reads in US landings by stat area, associates NESPP3 codes with Atlantis groups. Exports rds
*  `create_stockSMART_catch_data.r` - filters stocksmart data by stocks in north atlantic, and associates with Atlantis groups. Exports rds
*  `create_nafo_21a_catch_data.r` - reads in nafo 21 data, associates species codes with Atlantis groups. `nafo_neus_codes.csv`. Exports rds
* `create_other_catch_data.r`. Reads in Menhaden data as own data source
* `create_neus_catch_data.r` - reads in 4 rds (stocksmart, nafo, comlandr,other) files, imputes (`impute_catch.r`) missing stocksmart years, imputes missing comlandr data (`impute_catch2.r`), scales NAFO live weight (for shell fish) to meat weight, then combines 4 data sources (`select_source.r`) to result in `neusCatchData.rds` . Stocksmart data is used for some species, comlandr +NAFO for others. This is defined in `functionalGroupNames_catchsource.csv`

## Plotting

* `plot_box_statarea.r` updated to display neus footprint compared with stat areas and nafo divisions
* `spatialFootprints.png` displaying differences between spatial footprints of us landings, NAFO and NEUS

## Method documentation

* `createCatchData.rmd` - steps through process and outlines caveats/work still to do

## Note:  intermediate data products were not committed 
*  UScomland ,NAFO, Stocksmart aggregated over time to atlantis groups 
* NAFO 21A data was not committed
* comlandr pulls not committed

### CODE REVIEW

**Comment by andybeet** [comment]
@jcaracappa1 @RGamble1 Will upload a comparison plot of old neus data with this new product for review later today. Also catch includes stat areas 625 (Chesapeake bay, this area also includes a significant portion of MAB coastline) and 611 (Long island sound). Also note that many of the statistical areas overlap with the boundary boxes.

**Review by RGamble1 — APPROVED** [review]
Looks good to me: @andybeet, @jcaracappa1

**Comment by andybeet** [comment]
@jcaracappa1 Updated comparison. HMS species now use comlandr, Menhaden uses "northern" stock definition. Bug fixes for COD, HAD, POL, GOO, WIF. (Catch was doubled)
neusComparison

**Comment by jcaracappa1** [comment]
@Ran catch comparisons and confirmed that prior version was scaled to lower catch from assumptions that are no longer valid. Will have to work on fixing species that are crashing and possibly increase the starting biomass.

**Pull request merged**
