### PR TITLE
Planktivore persist atlnts 7

### PR DESCRIPTION
**Pull request by gambler1650**
@andybeet, @jcaracappa1 

* Fixed a recruitment issue with Herring related to a bug in the code if it happens too late in the year
    + This is a fudge, and needs to be reverted once the bug is fixed in Atlantis
* Fixed the lower trophic levels that herring and mackerel rely on, to persist at levels at which starvation isn't an issue
    + Increased the initial biomasses of phytoplankton and zooplankton groups
    + Tweaked the pprey values between the lower trophic levels to keep species from being preyed upon enough to crash
* Increased initial biomass values for Mackerel and Herring
* Increased recruits per year for Mackerel and Herring
* Increased assimilation efficiency for Mackerel and Herring
    + Mackerel persists at resonable levels
    + Herring still collapses at time step 51 with normal fishing
* Changed the age structure of the catch for Mackerel and Herring to prevent overfishing at lower age classes
* Affects: at_biology_test.prm, at_run_test.prm, at_harvest_test.prm

### CODE REVIEW

**Comment by jcaracappa1** [comment]
@andybeet @gambler1650 I'm not sure i understand when a merge conflict is generated. For instance, in the at_run_test.prm file Rob changes has a different "tstop" than what's in the master, but it does not show that as a change. Also Rob's at_force_WIN_test.prm should show changes since the master has a lot of additional lines that aren't in his files.

**Comment by andybeet** [comment]
@jcaracappa1 @gambler1650 I see rob has tstop as 18260 in his [branch](https://github.com/NOAA-EDAB/neus-atlantis/blob/PlanktivorePersist-ATLNTS-7/testing/at_run_test.prm) and I see the [master](https://github.com/NOAA-EDAB/neus-atlantis/blob/PlanktivorePersist-ATLNTS-7/testing/at_run_test.prm) has the same value. 

And i don't see that Rob changed anything in the at_force file. Are you seeing something that i am not?

It is only merging changes made to files. If the master gets ahead but no changes are made on the branch then nothing will get merged

**Comment by jcaracappa1** [comment]
@andybeet @gambler1650 The last part answers one question. No, Rob didn't make any changes to the at_force file, I was just mixing up what happens during a merge

Regarding the at_run file. I see 18608 in the [master ](https://github.com/NOAA-EDAB/neus-atlantis/blob/master/testing/at_run_test.prm). I think you linked the branch twice by mistake. But since ROM never made a change to tstop, the master is ahead of his branch for that line. If it's not recognizing that as a change, then it should keep what's in the master currently instead of overwriting it, right?

**Comment by andybeet** [comment]
yes i did mistakenly link to the branch twice! But what you said is correct. Rob never made a change to tstop so the master stays as is

**Comment by jcaracappa1** [comment]
Okay. Thank make sense. Sorry for the holdup then. In that case, everything looks good.

**Pull request merged**
