### PR TITLE
Atlnts 155 (retuning migratory pelagics)

### PR DESCRIPTION
**Pull request by gambler1650**
## Retune previously tuned species (ATLNTS-155)
 * RG: 10-18-2020
 * Increased BFT C and mum parameters
 * Increased growth rates outside the model
 * Increased survivorship outside the model to take into account predation on juveniles and fishing.
 * BFT currently crashes in the middle of the run but return near the end to normal levels.  Since they aren't a huge player in the model, I am calling this 'done' for now.

### CODE REVIEW

**Comment by jcaracappa1** [comment]
@andybeet This looks good!

**Comment by jcaracappa1** [comment]
@andybeet @gambler1650 Any idea what happens when we have 2 simultaneous merges?

**Comment by gambler1650** [comment]
> @andybeet @gambler1650 Any idea what happens when we have 2 simultaneous merges?

@andybee @jcaracappa1  So, I discovered what happens.  I merged Joe's request and then there was a conflict as Joe changed the recruits for TUN and BFT (as did I).  

It takes you to a conflict page, and I deleted the rows on Master (Joe's version) and kept mine (since it seems to keep BFT and TUN at reasonable levels).  It now says all conflicts are resolved and it can be merged.  However, I want to make sure that no one has any issues with doing so, before doing so.

**Comment by andybeet** [comment]
looks good to me too. @gambler1650 Did you want to merge it?

**Comment by jcaracappa1** [comment]
@gambler1650 Ok. I was hoping that's how it worked. Yes, keep your changes and remove any conflicts that I made for the tuna.

**Pull request merged**
