### PR TITLE
Atl batcher

### PR DESCRIPTION
**Pull request by gambler1650**
Removed all hard coded paths except for two variable names.  We can later make those more general.  @jcaracappa1 @andybeet

### CODE REVIEW

**Comment by jcaracappa1** [comment]
@gambler1650 @andybeet So I tried testing this but it hangs up at "WaitIndex = 26" with your test set files. There was a ton of stuff printed to command line that I had a hard time following. Is it normal to print a bunch of stuff from the log.txt?

**Comment by gambler1650** [comment]
> @gambler1650 @andybeet So I tried testing this but it hangs up at "WaitIndex = 26" with your test set files. There was a ton of stuff printed to command line that I had a hard time following. Is it normal to print a bunch of stuff from the log.txt?

That's actually all debug stuff that isn't intended to go to the log file.  Checking on it, seems to work fine on my end.

**Comment by jcaracappa1** [comment]
@gambler1650 @andybeet It looks like I had a hidden container that didn't have the right exit code or something causing the skipping in the batcher. I reset the background container list and the function worked. I think it's fine to merge.

**Comment by andybeet** [comment]
I haven't had time to test. Will assume its ok. i will merge and test later. Dont want to hold things up

**Pull request merged**
