### PR TITLE
Fix goo mak

### PR DESCRIPTION
**Pull request by jcaracappa1**
## Summary

- Fixed bugs in inital conditions numbers/size at age scaling
- Several adjustments to groups thereafter
- Improved GOO (still not working)
- Slight improvments to MAK, SCA, and LOB
- Many improvements to other species after initial conditions changes

## Parameter Changes
- at_biology.prm: Clearance/growth rate changes to SCA, BC, LOB, MAK, HER, WHK, PLA, COD, BSB, TYL, OPT, HAD, SMO, and WSK; decrease SCA_mQ, increase recruitment for GOO
- at_run.prm: Set MAK init scalar to 1
- neus_init.nc : Set GOO RN:SN at start to 0.5. Rescale initial numbers based on updated size-at-age proportion (mode around agecl 3-4 ).
- updated size at age diagnostics based on initial condition changes

## Other Changes
- .gitignore: fixed cases to work on Linux
- R/edit_param_invert_c_mum.R : added function to retrieve invert mum/C
- R/edit_param_mum-age.R : Added info to failing species
- R/make_fish_condition_rescale.R : Fixed bug in newly generated arrays
- R/make_initial_numbers_rescale.R : Added RN:SN column
- R/plot_yearlyoutput.R and R/plot_yearlyoutput_functions.R : Script from Hem to diagnose migrations
- R/process_atl_output.R : Added some memory management, stnadardized file extentions, and fixed dietcheck bug
- R/scale_mumC_age.R : Script to apply scalar to groups' mum/C

### CODE REVIEW

**Comment by jcaracappa1** [comment]
@gambler1650 @andybeet Intermediate fix for GOO, MAK, HER, SCA, and LOB. Some code changes and bug fixes.

**Comment by gambler1650** [comment]
@andybeet @jcaracappa1 
Looks good to me...

**Comment by andybeet** [comment]
I see a lot more changes in the biology file than just GOO, MAK, HER, SCA, and LOB. eg WHK, PLA, COD, BSB + others. Also the RunAtlantis.sh should probably be reverted back to use `at_biology.prm` instead of `at_biology_4.prm`

**Comment by jcaracappa1** [comment]
[ Fix GOO MAK (Pull Request 172)Model_Comparison_Biomass.pdf](https://github.com/NOAA-EDAB/neus-atlantis/files/9303427/Fix.GOO.MAK.Pull.Request.172.Model_Comparison_Biomass.pdf)

**Comment by jcaracappa1** [comment]
@andybeet I cleared up the summary and fixed that error in the run.sh

**Pull request merged**
