### PR TITLE
Atlnts 215 remove salmon catch

### PR DESCRIPTION
**Pull request by jcaracappa1**
Set catch timeseries in totalcatch.ts to 0 for Atlantic Salmon (SAL). 
Added line specifically for SAL in make_catch_file.R

### CODE REVIEW

**Comment by andybeet** [comment]
@jcaracappa1 what is total_catch_new.txt?

**Comment by jcaracappa1** [comment]
@andybeet Just a text file with the same output as total_catch.ts . It's the output from make_catch_file.R

**Comment by andybeet** [comment]
@jcaracappa1 @gambler1650 Looks good

**Comment by gambler1650** [comment]
Looks good to me too.

**Pull request merged**
